[package]
name = "rastfm"
version = "0.1.2"
authors = ["user <noemail@nowhere.net>"]

[dependencies]
regex="0.2"
hyper="0.11"
serde_json="1.0"
serde_urlencoded = "0.5"
rust-crypto="0.2"
futures="0.1"
tokio-core="0.1"

